version: '3.9'
services:
  app:
    build: 
      context: .
    ports:
      -"8000:8000"
    volumes:
      - .:/code/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]